### ISSUE TITLE
Crew management problem(New AI Update "Henchman") problem And Bag issue (maybe found a way to fix it) And Offshore Payday loot screen crash issue (maybe found a way to fix it)

### ISSUE THREAD

**Issue by Jacky10X** [polarathene/biglobby#47]
Now Payday 2 Change their AI system so AI has more improvement about it we can manage our AI but we can only custom 3 AI. if we have more than 3 AIs.  The no.4 AI and above will be random and have not any affect (such as buff) i mean is there any way that we can custom our AI more than 3?(we can custom our AI as same as our big lobby AI) also if we even disable the bot(big lobby option) the bot is still be 4 not 3 Sorry for my bad English

**Comment by Jacky10X** [comment]
IN pdmod src/mod/network.network_settings 
maybe we change 		
<message name="biglobby__sync_equipment_setup" delivery="ordered" receiver="biglobby__unit" check="server_to_client">
			<param type="unit" />
			<param type="float" min="0" max="2" />
			<param type="int" min="0" max="128" /> 
		</message>
to
<message name="biglobby__sync_equipment_setup" delivery="ordered" receiver="biglobby__unit" check="server_to_client">
			<param type="unit" />
			<param type="float" min="0" max="255" />
			<param type="int" min="0" max="128" /> 
		</message>
to fix the issue (just maybe we can)

**Comment by Jacky10X** [comment]
Bag issue fix solution(maybe)
In pdmod src/mod/network.network_settings
Change
```
		<message name="biglobby__sync_equipment_setup" delivery="ordered" receiver="biglobby__unit" check="server_to_client">
			<param type="unit" />
			<param type="float" min="0" max="2" />
			<param type="int" min="0" max="128" /> <!-- Peer id -->
		</message>
```
to
```
		<message name="biglobby__sync_equipment_setup" delivery="ordered" receiver="biglobby__unit" check="server_to_client">
			<param type="unit" />
			<param type="float" min="0" max="255" />
			<param type="int" min="0" max="128" /> <!-- Peer id -->
		</message>
```
to fix the bag issue(maybe) [we can only saw two bags when there are actually four bags]

**Comment by rockr230** [comment]
@Jacky10X Probably want to mention the possible bag fix in issue #43 (assuming you're also talking about the Doctor Bags)

**Comment by Jacky10X** [comment]
@rockr230 Yes i am talking about the medic bags issue but what happen about the first aid kits?(just saw your issue but i still don't understand what is the problem)

**Comment by rockr230** [comment]
@Jacky10X I updated the issue with a (hopefully) clearer explanation on the First Aid Kit issue

**Comment by polarathene** [comment]
I only have time to update network methods, if the update changed other code that breaks BigLobby I'm unfortunately able to find time to fix it. If anyone wants to try and has questions about BigLobby code they are welcome to ask me and create a PR with a fix to review.

The bag one can be fixed, thanks for identifying the network method, it looks like at some point I updated the original with the 255 value but missed the biglobby version. I may find time to handle updating this file with BigLobby changes automatically with a small tool instead of manual to avoid this problem in future. It could be possible that some other updates were missed there too.

**Comment by Jacky10X** [comment]
Payday 2 release second update 147 to fix the Desync problem But i think it may change the network method/function

**Comment by Jacky10X** [comment]
Well there only last bug we still can't fix (rockr230 mention) is the Upper aced auto-use feature (maybe author can look at this bug) [Edit: test it and it is work So i think this is not the mod problem]

**Comment by polarathene** [comment]
> maybe author can look at this bug

If you're referring to me, I don't have time to dive through paydays codebase and try figure these things out, else the other biglobby features would be completed by now. I just provide maintenance updates with network methods.

The bag issue as stated can be fixed, I've made the change but not pushed an update. When there is more network changes with an update from pd2 I'll push another biglobby sync update.

```xml
		<message name="biglobby__sync_equipment_setup" delivery="ordered" receiver="biglobby__unit" check="server_to_client">
			<param type="unit" />
			<param type="float" min="0" max="255" />
			<param type="int" min="0" max="128" /> <!-- Peer id -->
		</message>
```

Is the change you can make to the network.network_settings file. Updating the pdmod with that change is pretty easy.

---

I would be happy to review fixes from others to add to biglobby :)

**Comment by Souyu** [comment]
Sorry, newbie to payday 2 modding, but how would I be able to update the pdmod with the change?

**Comment by Jacky10X** [comment]
@polarathene

**Comment by Jacky10X** [comment]
@rockr230 @polarathene   Hey i just test the first aid kid with upper skill aced and it is work [have not modify anything] So i think it is not about the mod problem [i just click the close issue by accident]

**Comment by polarathene** [comment]
@Souyu 

- Take [this file](https://github.com/polarathene/biglobby/blob/master/pdmod%20src/mod/network.network_settings)(you can click the button at top of the text that says `Raw`, 
- then ctrl+a, ctrl+c to copy all the raw text, 
- open up notepad and paste ctrl+v and save it as `network.network_settings`.

- Search(ctrl+f) for `biglobby__sync_equipment_setup`, 
- you should see a couple lines below it `<param type="float" min="0" max="2" />`, 
- update the max value to 255 so it looks like `<param type="float" min="0" max="255" />`. 
- Save this file(ctrl+s).

- Use the Payday Bundle Modder tool that lets you apply .pdmod files, 
- save [this file](https://github.com/polarathene/biglobby/blob/master/pdmod%20src/BigLobby%20-%20Set%20Player%20limit%20to%20128.txt) like above, the filename doesn't matter. 
- On bundle modder tool, click the `Create Mod` tab, then `Load PDMod Project`, choose the file. 
- It will have one value/row listed under `Replacement Files`, this is not correct path for your system, click it and press `Remove Selected Replacement(s)` button. 
- Click the `Browse` button above that and choose the `network.network_settings` file you saved earlier.
- In the `bundle file name` field above that, change it to `settings/network.network_settings`. 
- Click `Add Replacement To Mod`, 
- at bottom left click the `Create Mod` button. 
- Save the file as whatever you want, then load it like any other pdmod, disable the previous biglobby one.

After all that you should have an updated pdmod.

**Comment by polarathene** [comment]
@Jacky10X ok good to know. So only issue left for you is the AI, but AI works same as before, it is not broken correct? You just wanted to use the new customize AI feature on all other bots?

**Comment by Jacky10X** [comment]
@polarathene Yes and it seem likes if we disable the bot option(biglobby one) there always one extra bot here (4 bots instead of 3) i don't know is it payday 2 official set for it (maybe max lobby slot is 4 and set the AI default is 4) or something else? for example, if i open the 5 player room and i disable the bot option(big lobby) there will be me + 4 bots  but not me + 3 bots

**Comment by polarathene** [comment]
@Jacky10X The code for bot support on biglobby is very small, you can see it [here](https://github.com/polarathene/biglobby/blob/master/biglobby/lua/lib/managers/_criminalsmanager.lua). 

Bots should only be different when enabled, I'm not sure why you have extra bot compared to biglobby disabled. Maybe the MAX_NR_CRIMINALS, affect it, or MAX_NR_TEAM_AI was not reset(can confirm by restarting pd2).

---

The AI improvement to apply to all bots belongs to another mod or for someone to contribute. Perhaps talk to mod author for BetterBots, I'm not sure if it allows extra bot and had similar problem? Maybe he fix it. Bot support on biglobby is not focus of biglobby(playing with more than 4 humans is).

**Comment by rockr230** [comment]
@Jacky10X Regarding the first aid kit/doctor bag issue, when I tested it, I had all no other mods, and the issue that clients have still occurs. Hosts can always use the upgrades, but clients can't for some reason. And I tested this with a friend as a client and host.

**Comment by polarathene** [comment]
@rockr230 have you tried patching `biglobby__sync_equipment_setup` as described above? I'm not sure if all players need to run it since it's `server to client`.

I don't mod PD2 anymore, but presumably you could track down the logic that does the issue you're describing(with biglobby disabled), and see why it's not working with biglobby. Usually it's due to a network method, which as far as I can tell beyond the sync_equipment one mentioned here, should be correct. There is also a chance that the globals lua file which needs to list the biglobby versions might be missing one by mistake. This method mentioned [exists there](https://github.com/polarathene/biglobby/blob/master/biglobby/lua/_custom/biglobby_globals.lua#L100) though.

**Comment by Jacky10X** [comment]
i ask author for BetterBots and he/she says he/she can not help about the crew management problem

**Comment by polarathene** [comment]
@Jacky10X then I guess it will not happen? If someone wants to make mod for it then great, but unless using biglobby there probably isn't much motivation for someone to do that. This mod is not that popular anymore. The feature you want might require alot of time to make I think :(

**Comment by polarathene** [comment]
Hi, I've pushed an update with the network method changes. [v2.44](https://github.com/polarathene/biglobby/releases/tag/v2.44) contains the biglobby bugfix here that updates `biglobby__sync_equipment_setup` from a value of **2** to **255**. Maybe it fixes the equipment issues some of you had before.

**Comment by Jacky10X** [comment]
@polarathene 
hello i am sorry too late to tell you
but it seems like we can't disable allow-more-bots-in-lobby option
if we disable the option and the option will enable it automatic

For example,
You can try to disable the disable allow-more-bots-in-lobby option first
And then open any heist
when you start the heist 
you will find there are 4 bots but not 3 bots 
(If you disable allow-more-bots-in-lobby, it should be 3 bots but not 4 bots)
And you can find the allow-more-bots-in-lobby option is enabled automatic

i think it may cause we always has 4 bots instead of 3 even if we disable allow-more-bots-in-lobby option
It is because it will enable it automatic

**Comment by polarathene** [comment]
@Jacky10X You get 4 bots no matter what setting you use? Do you get different amount if you don't have biglobby enabled? If so disable the bot option setting, exit game, start payday again biglobby mod should be enabled and the setting is still disabled, then try and see if problem is still there. If reset fix it, you will find that start a game, then exit back to menu after loaded into level will also fix it.

If that is not the case, then bug is because of some code change by game developer. You can disable by editing [this file, 2nd line](https://github.com/polarathene/biglobby/blob/master/biglobby/lua/lib/managers/_criminalsmanager.lua#L2), set the number to what you want instead of `BigLobbyGlobals:num_bot_slots()` or delete the line and biglobby will not modify.

**Comment by Jacky10X** [comment]
@polarathene i think biglobby/biglobby/lua/_custom/menu.lua may cause the option keeps enabled
because it seems like the option is keeping set it to true but there is no false condition
Also i think maybe change "self._constants.UNIQUE_HEISTERS = 16" to 18 (in the future it may change it to 19)

**Comment by polarathene** [comment]
@Jacky10X the start of the menu.lua is to load the settings saved to json file like other mods do or use a default. The heisters number is also just used for defaults, it could be bumped up to match whatever is unique heister number atm sure.

The actual problem/bug is down further in the menu.lua file where the checkbox variable name is incorrect. I will fix it for next release update. Thankyou for spotting it.

**Comment by Jacky10X** [comment]
@polarathene there's one thing is if we get loading screen the checkbox will reset it to enable

**Comment by Jacky10X** [comment]
@polarathene 
Hi i am sorry to bother you again
i found something that if we go to Offshore Payday loot screen it may cause the crash
the fix solution (Maybe) is go to biglobby/lua/lib/managers/hud/_hudlootscreen.lua 
find line 10
    change
        `if HUDLootScreen._init_extra_peers then`
    to
        `if HUDLootScreen._init_extra_peers or (table.getn(self._peer_data) == 4 and num_player_slots > 4) then`

i don't know what happen but it seem it will change back to original peers if we don't modify it

**Comment by Jacky10X** [comment]
@polarathene do you see the Offshore Payday loot screen crash possible solution above?

**Comment by polarathene** [comment]
@Jacky10X I've pushed the change you've suggested into [this commit](https://github.com/polarathene/biglobby/commit/742099ec17875ce54be3af1a20ccfd1885bf2112). I don't play the game anymore, this only gets updates if other users contribute.

There is some community members that are working on taking over the project and maintaining it elsewhere, they've had some success in not requiring a pdmod for this anymore which is great news :)

If I receive another PR for the next update to network methods, I'll release with this change.

**Comment by Shad0wlife** [comment]
Ok, I tried looking through this.
What I found still existing:
- The mod has no support for henchmen customization and priorizing which char to use for henchmen (nobody implemented it, so that's obvious)
- The Allow More Bots setting does not stay turned off when loading into a heist (preparation screen, setting the option off from there keeps it off for the mission)

**Comment by polarathene** [comment]
@Shad0wlife Correct, this mod was made well before the henchmen feature, and was in in maintenance mode by that point. Welcome to add support via PR.

The 2nd issue is likely due to how BLT works(or worked at the time). Similar to how if you change settings at crime.net I think, they only apply once you trigger BLT to reload all mods and run their code(which also resets a bunch of variables and runs other code iirc independent of any mod, probably way game works rather than something BLT does). Once you've loaded mission briefing screen, it's done that, so changes at this point won't reflect until you go back to crime.net I think(triggers another "refresh").

If you have a way to apply certain settings that behave undesirably without requiring a "refresh"(in BLT logs you notice all mods get loaded again), then by all means send a PR :)

**Comment by Jacky10X** [comment]
@polarathene it's seem some people create another biglobby mod that doesn't require pdmod
but you need specific BLT call superBLT 
https://modworkshop.net/mydownloads.php?action=view_down&did=21582

**Comment by polarathene** [comment]
@Jacky10X yes, I approved it :) I had not been informed yet of the release so thanks for the link. That group is meant to continue biglobby mod as far as I know, since I do not have time for it anymore.
